version: '3.8'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: study_diary
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - study_diary:/var/lib/postgresql/data
volumes:
  study_diary:
