version: '3'
services:
  app:
    build: ./app
    context: .
    dockerfile: ./app/dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: study_diary
    volumes:
      - ./:/study_diary
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
