staging:
  adapter: "postgresql"
  database: <%= ENV['POSTGRES_DB'] %>
  encoding: "utf8"
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  reconnect: true
  port: 5432

production:
  adapter: "postgresql"
  database: <%= ENV['POSTGRES_DB'] %>
  encoding: "utf8"
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  reconnect: true
  port: 5432

test:
  adapter: postgresql
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 20
  timeout: 5000
  template: template0
  adapter: postgresql


