development:
  adapter: postgresql
  encoding: unicode
  database: study_diary_development
  pool: 5
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: study_diary_test
  pool: 5
  username: postgres
  password: postgres

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 
