development: &default
  adapter: postgresql
  encoding: unicode
  database: study_diary_development
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: study_diary_test
  pool: 5
  username: postgres
  password: postgres
  port: 5432


staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
